<a href="https://colab.research.google.com/github/JaimeTS/hyrox-analysis/blob/main/notebooks/01_scraping_hyrox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

print("Entorno preparado correctamente")

Entorno preparado correctamente

In [2]:
import requests

url = "https://www.hyresult.com/event/s8-2026-barcelona"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print("Código de estado:", response.status_code)
print("Longitud del HTML:", len(response.text))

Código de estado: 200
Longitud del HTML: 139187

In [3]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

print(soup.title)

<title>HYROX Barcelona 2026</title>

In [4]:
links = []

for a in soup.find_all("a", href=True):
    href = a["href"]
    texto = a.get_text(strip=True)
    links.append((texto, href))

# Mostrar los primeros 30
for l in links[:30]:
    print(l)

('Home', '/')
('Events', '/events')
('Compare', '/compare')
('Rankings', '/rankings')
('All Time Ranking', '/rankings/alltime')
('Legends Ranking', '/rankings/legends')
('Elite Points Ranking', '/rankings/elite-points/singles-men')
('Simulator', '/simulator')
('Locations', '/locations')
('Home', '/')
('Compare', '/compare')
('Events', '/events')
('Simulator', '/simulator')
('Locations', '/locations')
('Rankings', '/rankings')
('HYROX Guide', '/hyrox')
('Run', '/hyrox/run')
('SkiErg', '/hyrox/ski-erg')
('Sled Push', '/hyrox/sled-push')
('Sled Pull', '/hyrox/sled-pull')
('Burpee Broad Jump', '/hyrox/burpee-broad-jump')
('Row', '/hyrox/row')
('Farmers Carry', '/hyrox/farmers-carry')
('Sandbag Lunges', '/hyrox/sandbag-lunges')
('Wall Balls', '/hyrox/wall-balls')
('About', '/about')
('Partner', '/partner')
('Privacy', '/privacy')
('Legal', '/legal')
('@hyresult', 'https://www.instagram.com/hyresult/')

In [5]:
import pandas as pd

links_df = pd.DataFrame(links, columns=["texto", "href"])

# Filtramos enlaces que parezcan rankings
ranking_links = links_df[
    links_df["href"].str.contains("ranking", case=False, na=False)
].drop_duplicates()

ranking_links

                   texto                                               href
3               Rankings                                          /rankings
4       All Time Ranking                                  /rankings/alltime
5        Legends Ranking                                  /rankings/legends
6   Elite Points Ranking                 /rankings/elite-points/singles-men
40               Ranking               /ranking/s8-2026-barcelona-hyrox-men
41               Ranking             /ranking/s8-2026-barcelona-hyrox-women
42               Ranking       /ranking/s8-2026-barcelona-hyrox-doubles-men
43               Ranking     /ranking/s8-2026-barcelona-hyrox-doubles-women
44               Ranking     /ranking/s8-2026-barcelona-hyrox-doubles-mixed
45               Ranking           /ranking/s8-2026-barcelona-hyrox-pro-men
46               Ranking         /ranking/s8-2026-barcelona-hyrox-pro-women
47               Ranking   /ranking/s8-2026-barcelona-hyrox-pro-doubles-men
48               Ranking  /ranking/s8-2026-barcelona-hyrox-pro-doubles-w...
49               Ranking    /ranking/s8-2026-barcelona-hyrox-team-relay-men
50               Ranking  /ranking/s8-2026-barcelona-hyrox-team-relay-women
51               Ranking  /ranking/s8-2026-barcelona-hyrox-team-relay-mixed
52               Ranking      /ranking/s8-2026-barcelona-hyrox-adaptive-men
53               Ranking    /ranking/s8-2026-barcelona-hyrox-adaptive-women

In [6]:
ranking_url = "https://www.hyresult.com/ranking/s8-2026-barcelona-hyrox-men"

response_rank = requests.get(ranking_url, headers=headers)

print("Código:", response_rank.status_code)
print("Longitud:", len(response_rank.text))

Código: 200
Longitud: 664556

In [7]:
from bs4 import BeautifulSoup

soup_rank = BeautifulSoup(response_rank.text, "html.parser")

tables = soup_rank.find_all("table")

print(f"Número de tablas encontradas: {len(tables)}")

Número de tablas encontradas: 102

In [8]:
# Mostrar el tamaño de todas las tablas
for i, table in enumerate(pd.read_html(response_rank.text)):
    print(f"Tabla {i}: {table.shape}")

/tmp/ipykernel_4481/323201786.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  for i, table in enumerate(pd.read_html(response_rank.text)):

Tabla 0: (3, 7)
Tabla 1: (1, 1)
Tabla 2: (1, 1)
Tabla 3: (1, 1)
Tabla 4: (1, 1)
Tabla 5: (1, 7)
Tabla 6: (1, 7)
Tabla 7: (1, 7)
Tabla 8: (1, 7)
Tabla 9: (1, 7)
Tabla 10: (1, 7)
Tabla 11: (1, 7)
Tabla 12: (1, 7)
Tabla 13: (1, 7)
Tabla 14: (1, 7)
Tabla 15: (1, 7)
Tabla 16: (1, 7)
Tabla 17: (1, 7)
Tabla 18: (1, 7)
Tabla 19: (1, 7)
Tabla 20: (1, 7)
Tabla 21: (1, 7)
Tabla 22: (1, 7)
Tabla 23: (1, 7)
Tabla 24: (1, 7)
Tabla 25: (1, 7)
Tabla 26: (1, 7)
Tabla 27: (1, 7)
Tabla 28: (1, 7)
Tabla 29: (1, 7)
Tabla 30: (1, 7)
Tabla 31: (1, 7)
Tabla 32: (1, 7)
Tabla 33: (1, 7)
Tabla 34: (1, 7)
Tabla 35: (1, 7)
Tabla 36: (1, 7)
Tabla 37: (1, 7)
Tabla 38: (1, 7)
Tabla 39: (1, 7)
Tabla 40: (1, 7)
Tabla 41: (1, 7)
Tabla 42: (1, 7)
Tabla 43: (1, 7)
Tabla 44: (1, 7)
Tabla 45: (1, 7)
Tabla 46: (1, 7)
Tabla 47: (1, 7)
Tabla 48: (1, 7)
Tabla 49: (1, 7)
Tabla 50: (1, 7)
Tabla 51: (1, 7)
Tabla 52: (1, 7)
Tabla 53: (1, 7)
Tabla 54: (1, 7)
Tabla 55: (1, 7)
Tabla 56: (1, 7)
Tabla 57: (1, 7)
Tabla 58: (1, 7)
Tabla 59: (1, 7)
Tabla 60: (1, 7)
Tabla 61: (1, 7)
Tabla 62: (1, 7)
Tabla 63: (1, 7)
Tabla 64: (1, 7)
Tabla 65: (1, 7)
Tabla 66: (1, 7)
Tabla 67: (1, 7)
Tabla 68: (1, 7)
Tabla 69: (1, 7)
Tabla 70: (1, 7)
Tabla 71: (1, 7)
Tabla 72: (1, 7)
Tabla 73: (1, 7)
Tabla 74: (1, 7)
Tabla 75: (1, 7)
Tabla 76: (1, 7)
Tabla 77: (1, 7)
Tabla 78: (1, 7)
Tabla 79: (1, 7)
Tabla 80: (1, 7)
Tabla 81: (1, 7)
Tabla 82: (1, 7)
Tabla 83: (1, 7)
Tabla 84: (1, 7)
Tabla 85: (1, 7)
Tabla 86: (1, 7)
Tabla 87: (1, 7)
Tabla 88: (1, 7)
Tabla 89: (1, 7)
Tabla 90: (1, 7)
Tabla 91: (1, 7)
Tabla 92: (1, 7)
Tabla 93: (1, 7)
Tabla 94: (1, 7)
Tabla 95: (1, 7)
Tabla 96: (1, 7)
Tabla 97: (1, 7)
Tabla 98: (1, 7)
Tabla 99: (1, 7)
Tabla 100: (1, 7)
Tabla 101: (1, 7)

In [9]:
df = pd.read_html(response_rank.text)[0]

df.head(10)

/tmp/ipykernel_4481/253504753.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response_rank.text)[0]

   Unnamed: 0  #  # AG     Unnamed: 3     AG   Time Unnamed: 6
0         NaN  1     1  Gaetan Gianni  16-24  53:44    Analyze
1         NaN  2     1  Emilio Aguayo  35-39  56:38    Analyze
2         NaN  3     1            NaN    NaN    NaN        NaN

In [11]:
df.columns

Index(['Unnamed: 0', '#', '# AG', 'Unnamed: 3', 'AG', 'Time', 'Unnamed: 6'], dtype='object')

In [12]:
tablas = pd.read_html(response_rank.text)

for i, df in enumerate(tablas):
    if len(df) > 20:   # Solo mostramos tablas con bastantes filas
        print(f"\n===== Tabla {i} =====")
        print(df.head(3))
        print(df.columns)

/tmp/ipykernel_4481/714115673.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tablas = pd.read_html(response_rank.text)

In [13]:
from io import StringIO

tablas = pd.read_html(StringIO(response_rank.text))

print("Número de tablas:", len(tablas))

# Vemos las primeras tablas
for i, t in enumerate(tablas[:10]):
    print(f"\nTabla {i}: {t.shape}")
    display(t.head())

Número de tablas: 102

Tabla 0: (3, 7)

   Unnamed: 0  #  # AG     Unnamed: 3     AG   Time Unnamed: 6
0         NaN  1     1  Gaetan Gianni  16-24  53:44    Analyze
1         NaN  2     1  Emilio Aguayo  35-39  56:38    Analyze
2         NaN  3     1            NaN    NaN    NaN        NaN

Tabla 1: (1, 1)

               0
0  Loic Cebelieu

Tabla 2: (1, 1)

       0
0  25-29

Tabla 3: (1, 1)

       0
0  57:17

Tabla 4: (1, 1)

         0
0  Analyze

Tabla 5: (1, 7)

    0  1  2                        3      4      5        6
0 NaN  4  1  Ferran Bochaca Sabarich  30-34  57:24  Analyze

Tabla 6: (1, 7)

    0  1  2                     3      4      5        6
0 NaN  5  2  Alberto Casado Aroca  30-34  57:38  Analyze

Tabla 7: (1, 7)

    0  1  2                    3      4      5        6
0 NaN  6  3  Sebastien Rajkowski  30-34  58:10  Analyze

Tabla 8: (1, 7)

    0  1  2                 3      4      5        6
0 NaN  7  4  Mehdi Berrouigat  30-34  58:19  Analyze

Tabla 9: (1, 7)

    0  1  2                    3      4      5        6
0 NaN  8  2  Pau Nacenta Merinas  25-29  58:35  Analyze

In [14]:
# Guardamos el HTML en un archivo para inspeccionarlo
with open("pagina_ranking.html", "w", encoding="utf-8") as f:
    f.write(response_rank.text)

print("HTML guardado correctamente")

HTML guardado correctamente

In [15]:
# Buscar las primeras ocurrencias de "Gaetan"
indice = response_rank.text.find("Gaetan")

print(indice)
print(response_rank.text[indice-500:indice+1000])

88164
currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check size-3.5 opacity-0" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></button></td><td class="p-2 pe-0 whitespace-nowrap">1</td><td class="p-2 hidden md:table-cell">1</td><td class="p-2 font-semibold whitespace-normal"><img src="https://cdn.hyresult.com/flags/fr.svg" alt="France" title="France" class="inline-block align-middle w-5 h-4 mb-0.5 me-2.5"/><a href="/athlete/gaetan-gianni">Gaetan Gianni</a></td><td class="p-2 hidden md:table-cell"><span data-slot="badge" data-variant="division" class="group/badge inline-flex h-5 w-fit shrink-0 items-center justify-center gap-1 overflow-hidden rounded-4xl border border-transparent px-2 py-0.5 text-xs font-medium whitespace-nowrap transition-all focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&amp;&gt;svg]:pointer-events-none [&amp;&gt;svg]:size-3! ml-2 border-none bg-zinc-900 text-gray-400 md:h-7 md:px-2">16-24</span></td><td class="p-2 font-mono text-right">53:44</td><td class="p-2 text-right text-md"><a title="Analyze race of Gaetan Gianni" role="button" tabindex="0" data-slot="button" class="group/button inline-flex shrink-0 items-center justify-center border border-transparent bg-clip-padding font-medium whitespace-no

In [16]:
from IPython.display import display, HTML

indice = response_rank.text.find("Gaetan")

fragmento = response_rank.text[indice-1500:indice+2500]

print("Índice:", indice)
print(fragmento)

Índice: 88164
="1"/></div><table class="table-fixed w-screen sm:w-full text-xs sm:text-sm md:text-base -mx-2 sm:mx-0"><thead><tr class="text-xs text-muted-foreground"><th class="w-[6%] hidden md:table-cell"></th><th class="w-[8%] p-2 pe-0 text-left">#</th><th class="w-[7%] p-2 text-left hidden md:table-cell"># AG</th><th class="w-[45%]"></th><th class="w-[10%] p-2 hidden md:table-cell">AG</th><th class="w-[20%] md:w-[13%] p-2 text-right">Time</th><th class="w-[12%] md:w-[15%]"></th></tr></thead><tbody><tr class="border-t border-t-zinc-700"><td class="py-2 ps-2 cursor-pointer hidden md:table-cell"><button type="button" role="checkbox" aria-checked="false" aria-label="Select athlete for comparison" class="relative flex size-4 shrink-0 items-center justify-center rounded-[4px] border border-input transition-colors outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check size-3.5 opacity-0" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></button></td><td class="p-2 pe-0 whitespace-nowrap">1</td><td class="p-2 hidden md:table-cell">1</td><td class="p-2 font-semibold whitespace-normal"><img src="https://cdn.hyresult.com/flags/fr.svg" alt="France" title="France" class="inline-block align-middle w-5 h-4 mb-0.5 me-2.5"/><a href="/athlete/gaetan-gianni">Gaetan Gianni</a></td><td class="p-2 hidden md:table-cell"><span data-slot="badge" data-variant="division" class="group/badge inline-flex h-5 w-fit shrink-0 items-center justify-center gap-1 overflow-hidden rounded-4xl border border-transparent px-2 py-0.5 text-xs font-medium whitespace-nowrap transition-all focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&amp;&gt;svg]:pointer-events-none [&amp;&gt;svg]:size-3! ml-2 border-none bg-zinc-900 text-gray-400 md:h-7 md:px-2">16-24</span></td><td class="p-2 font-mono text-right">53:44</td><td class="p-2 text-right text-md"><a title="Analyze race of Gaetan Gianni" role="button" tabindex="0" data-slot="button" class="group/button inline-flex shrink-0 items-center justify-center border border-transparent bg-clip-padding font-medium whitespace-nowrap transition-all outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 [&amp;_svg]:pointer-events-none [&amp;_svg]:shrink-0 bg-secondary text-secondary-foreground hover:bg-secondary/80 aria-expanded:bg-secondary aria-expanded:text-secondary-foreground h-7 gap-1 rounded-[min(var(--radius-md),12px)] px-2.5 text-[0.8rem] in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&amp;_svg:not([class*=&#x27;size-&#x27;])]:size-3.5" href="/result/LR3MS4JI502C48"><span class="hidden md:inline">Analyze</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right size-5 -mx-1" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></a></td></tr><tr class="border-t border-t-zinc-700"><td class="py-2 ps-2 cursor-pointer hidden md:table-cell"><button type="button" role="checkbox" aria-checked="false" aria-label="Select athlete for comparison" class="relative flex size-4 shrink-0 items-center justify-center rounded-[4px] border border-input transition-colors outline-none focus-visible:border-ring focus-visible:ring-3 focus-